name: Python program
on:
  workflow_dispatch
jobs:
  Runs_the_Python_Program:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    steps:
      - name: checkout content
        uses: actions/checkout@v2
      # - name: setup python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.11'
      - name: run python program
        run: python index.py
